"""
Seed skill_catalog from the canonical list (kept in sync with frontend fallback).
Run from project root: python -m scripts.seed_skill_catalog
"""

import asyncio

from sqlalchemy import delete
from sqlalchemy.dialects.postgresql import insert

from app.db.session import AsyncSessionLocal, init_db
from app.models.skill_catalog import SkillCatalog

# Same set as vertechie_fe-main/frontend/src/utils/skillSuggestions.ts (extend either side together).
CATALOG_SKILLS = sorted(
    {
        ".NET",
        "ADO.NET",
        "Agile",
        "Airflow",
        "Android",
        "Angular",
        "Ansible",
        "Apache Kafka",
        "ASP.NET",
        "AWS",
        "Azure",
        "Azure DevOps",
        "Bash",
        "BigQuery",
        "Blockchain",
        "Bootstrap",
        "C#",
        "C++",
        "Cassandra",
        "CI/CD",
        "CircleCI",
        "CloudFormation",
        "Computer Vision",
        "Confluence",
        "CSS3",
        "Cypress",
        "D3.js",
        "Databricks",
        "Data Science",
        "dbt",
        "Deep Learning",
        "Django",
        "Docker",
        "DynamoDB",
        "Elasticsearch",
        "Elixir",
        "Ember.js",
        "Express.js",
        "FastAPI",
        "Figma",
        "Firebase",
        "Flask",
        "Flutter",
        "GCP",
        "Git",
        "GitHub Actions",
        "GitLab CI",
        "Go",
        "Gradle",
        "GraphQL",
        "Grafana",
        "gRPC",
        "Hadoop",
        "Helm",
        "Hibernate",
        "HTML5",
        "Hugging Face",
        "iOS",
        "Istio",
        "Java",
        "JavaScript",
        "Jenkins",
        "Jest",
        "Jira",
        "jQuery",
        "JWT",
        "Kafka",
        "Kanban",
        "Keras",
        "Keycloak",
        "Kotlin",
        "Kubernetes",
        "LangChain",
        "Laravel",
        "Linux",
        "LLMs",
        "Machine Learning",
        "MATLAB",
        "Maven",
        "Microservices",
        "MLOps",
        "MongoDB",
        "Mongoose",
        "MySQL",
        "NestJS",
        "Next.js",
        "Node.js",
        "NLP",
        "Notion",
        "NumPy",
        "Nuxt.js",
        "OAuth",
        "Objective-C",
        "OpenAPI",
        "OpenCV",
        "Oracle",
        "OWASP",
        "Pandas",
        "Penetration Testing",
        "Perl",
        "PHP",
        "Playwright",
        "PostgreSQL",
        "Postman",
        "Power BI",
        "PowerShell",
        "Prometheus",
        "PySpark",
        "pytest",
        "Python",
        "PyTorch",
        "RabbitMQ",
        "React",
        "React Native",
        "Redis",
        "Redux",
        "Remix",
        "REST API",
        "Ruby",
        "Ruby on Rails",
        "Rust",
        "RxJS",
        "SAML",
        "Sass",
        "Scala",
        "scikit-learn",
        "Scrum",
        "Security",
        "Selenium",
        "Shell",
        "Shopify",
        "Slack",
        "Snowflake",
        "Solid.js",
        "Solidity",
        "Spark",
        "Spring Boot",
        "SQL",
        "SQL Server",
        "SQLite",
        "Storybook",
        "Supabase",
        "Svelte",
        "Swift",
        "Symfony",
        "Tableau",
        "Tailwind CSS",
        "TDD",
        "TensorFlow",
        "Terraform",
        "Three.js",
        "TypeORM",
        "TypeScript",
        "Unity",
        "Unix",
        "Vault",
        "Vercel",
        "Vim",
        "Visual Studio",
        "Vitest",
        "VS Code",
        "Vue.js",
        "Webpack",
        "WebSockets",
        "Xamarin",
        "YAML",
        "Zig",
        "Zustand",
    }
)


async def main() -> None:
    await init_db()
    count = 0
    async with AsyncSessionLocal() as session:
        for name in CATALOG_SKILLS:
            n = name.strip()
            if not n:
                continue
            stmt = insert(SkillCatalog).values(name=n).on_conflict_do_update(
                index_elements=["name"],
                set_={"name": n},
            )
            await session.execute(stmt)
            count += 1
        catalog_list = list(CATALOG_SKILLS)
        await session.execute(delete(SkillCatalog).where(~SkillCatalog.name.in_(catalog_list)))
        await session.commit()
    print(f"Seeded {count} skill catalog rows.")


if __name__ == "__main__":
    asyncio.run(main())
