/** App routes for E2E (paths only; use with baseURL from playwright.config). */
export const routes = {
  home: '/',
  login: '/login',
  signup: '/signup',
  techieSignup: '/techie-signup',
  signupCompany: '/signup/company',
  resetPassword: '/reset-password',
  techieHomeFeed: '/techie/home/feed',
  techieHomeNetwork: '/techie/home/network',
  techieHomeGroups: '/techie/home/groups',
  techieHomeEvents: '/techie/home/events',
  techieHomeCombinator: '/techie/home/combinator',
  techieJobs: '/techie/jobs',
  techieJob: (jobId: string) => `/techie/jobs/${jobId}`,
  techieJobApply: (jobId: string) => `/techie/jobs/${jobId}/apply`,
  techieAts: '/techie/ats',
  techieAtsPipeline: '/techie/ats/pipeline',
  techieAtsJobPostings: '/techie/ats/jobpostings',
  techieAtsAllCandidates: '/techie/ats/allcandidates',
  techieAtsCandidate: (candidateId: string) => `/techie/ats/candidate/${candidateId}`,
  techieAtsInterviews: '/techie/ats/interviews',
  techieAtsScheduling: '/techie/ats/scheduling',
  techieAtsCalendar: '/techie/ats/calendar',
  techieAtsAnalytics: '/techie/ats/analytics',
  hrCreateJob: '/hr/create-job',
  hrDashboard: '/hr/dashboard',
} as const;
